---
- name: Create user
  ansible.builtin.user:
    name: "{{ username }}"
    password: "{{ sudo_password }}"
    create_home: true
    generate_ssh_key: true
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    shell: /bin/bash
    groups: adm,users,sudo,dialout,cdrom,floppy,audio,dip,video,plugdev
    append: true
  changed_when: false

- name: Modify user bashrc
  ansible.builtin.lineinfile:
    path: "/home/{{ username }}/.bashrc"
    line: "{{ item }}"
    create: yes
  loop: "{{ bashrc_options }}"
